### ISSUE TITLE
bug(SSR): memory leak when using renderToString

### ISSUE THREAD

**Issue by eranhirs** [prescottprue/react-redux-firebase#357] opened 2017-12-10 18:44 UTC
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
I am rendering my redux app on the server using the `renderToString` method.
I stress-loaded the system with ApacheBench and the memory consistently grows over time.

After some profiling and reading [this code](https://github.com/firebase/firebase-js-sdk/blob/7db74e6111051eab499b0d3e95fb0789200cb14a/packages/app/src/firebaseApp.ts), it seems  `firebase/app.js` creates a lot of observers at initialization.

I've been using `react-redux-firebase` for a while.
Would love to know if someone run into something similar and how can I cancel this behavior.

**Comment by prescottprue** [comment] 2017-12-10 19:02
@eranhirs Really interesting use case (the stress loading sounds cool too).

Do you have a project you can share where you are doing this? Would love to replicate the issue so we can look into debugging.

**Comment by eranhirs** [comment] 2017-12-10 19:51
It seems the issue starts when I initialize `reactReduxFirebase` on every request, and each time [this code](https://github.com/firebase/firebase-js-sdk/blob/7db74e6111051eab499b0d3e95fb0789200cb14a/packages/app/src/firebaseApp.ts) is creating event listeners.

I don't have a project I can share, but I based my implementation on [this tutorial](https://medium.com/@benlu/ssr-with-create-react-app-v2-1-ee83fb767327).
There is a link to a github project.

**Comment by eranhirs** [comment] 2017-12-10 20:29
Initializing `reactReduxFirebase` once did the trick, thanks!

**Comment by eranhirs** [comment] 2017-12-10 23:35
So this wasn't the only problem.
It seems `componentWillUnmount` [is not called ](https://github.com/facebook/react/issues/3714)when calling `renderToString` .

I still see a lot of observers stacking up attached to an object in `auth`.
Any idea where are these observers created?
I see `firebaseConnect` [has a method](https://github.com/prescottprue/react-redux-firebase/blob/71a3e7781a77052afc7d0b3c979d385f66faad62/src/firebaseConnect.js) `watchEvents`.

**Comment by bastianwegge** [comment] 2018-02-22 13:03
Hey @eranhirs 👋,
do you maybe have the time to contribute a reproduction of your issue? I'd like to investigate but I can't find what you found without proper introduction to the code you're using. All the best!

**Comment by eranhirs** [comment] 2018-02-22 13:19
I understand, I suggest we close this for now and re-open once there is a reproduction of the problem.

**Comment by bastianwegge** [comment] 2018-02-22 14:48
You're pointing to a kind of serious error and I'm willing to help. Closing the Issue won't help. Do I understand correctly that this still occurs?

**Comment by eranhirs** [comment] 2018-02-22 14:53
Since updating `react-redux-firebase` to version 2 it seemed to improve.
I need to re-run the stress tests and profile my code to see if what I wrote earlier is still relevant.
Currently, we can close this.

**Comment by prescottprue** [comment] 2018-02-22 22:40
@eranhirs really great to hear, thanks for letting us know. @bastianwegge thanks for the help looking into it!

Going to close for now since it seems to have improved, but as mentioned we can always open again if there are steps to reproduce the issue.

**Closed by prescottprue** 2018-02-22 22:40 UTC
Labels: bug, help wanted, needs-repro
