### ISSUE TITLE
Require Cycle

### ISSUE THREAD

**Issue by tarunkishore2303** [prescottprue/react-redux-firebase#1023] opened 2020-11-17 05:36 UTC
### Bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/53224551/99348910-af9bfe80-28c0-11eb-87d9-84a09e25d0eb.png)

App keeps throwing me this error when combined with `react-native-firebase`. I suspect the firebase module in the `react-native-firebase` is causing this error

Link to [CodeSandbox](https://codesandbox.io/s/brave-framework-49mky)

Versions of the packages are specified in the `package.json`

**Comment by prescottprue** [comment] 2020-11-17 17:21
I believe this is a duplicate of #945 - Thanks for the repro, will link to the codesandbox on there

**Closed** 2020-11-17 17:24 UTC
