### ISSUE TITLE
bug(ordered): ordered not sync with data

### ISSUE THREAD

**Issue by geminiyellow** [prescottprue/react-redux-firebase#637] opened 2019-02-15 02:07 UTC
**What is the current behavior?**

![image](https://user-images.githubusercontent.com/929878/52829827-a1301a00-3111-11e9-9795-53d6597f3318.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

i just update firestore's data, and the local data was changed, but the ordered not

**What is the expected behavior?**

ordered should sync with data

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
"react-redux-firebase": "^2.2.6",
```

**Comment by prescottprue** [comment] 2019-02-16 09:06
I think this is a duplicate of [#121 on redux-firestore](https://github.com/prescottprue/redux-firestore/issues/121). If it is not, can you open another issue on [redux-firestore](https://github.com/prescottprue/redux-firestore) instead? It will be easier to track that way since that is where the reducer logic is contained.

**Closed by prescottprue** 2019-02-16 09:06 UTC

**Comment by geminiyellow** [comment] 2019-02-18 04:29
thank you @prescottprue , maybe it is caused by redux-firestore. keep tracking.
