### ISSUE TITLE
Cannot Add property _, object is not extensible

### ISSUE THREAD

**Issue by Cchumi** [prescottprue/react-redux-firebase#829] opened 2020-01-10 17:21 UTC
Hi just today I attempt to start a new project with react-redux-firebase (3.0.6), redux-firestore (0.11.0) and react-native-firebase (6.0.2).
EDIT: react-native (0.61.5) react (16.12.0)

So I follow your page and the result is the error message
**Cannot Add property _, object is not extensible**
This error is located at:
    in ReactReduxFirebaseProvider

```
import React from 'react'

import { Provider } from 'react-redux'
import RNFirebase from '@react-native-firebase/app';
//import firestore from '@react-native-firebase/firestore'

import thunk from 'redux-thunk'
import '@react-native-firebase/analytics';
import '@react-native-firebase/auth';
import '@react-native-firebase/crashlytics';
import '@react-native-firebase/dynamic-links';
import '@react-native-firebase/firestore'
import '@react-native-firebase/functions';
import '@react-native-firebase/perf';
import '@react-native-firebase/remote-config';
import '@react-native-firebase/messaging';
import '@react-native-firebase/storage';
import '@react-native-firebase/database';
import { createStore, combineReducers, compose } from 'redux'
import { ReactReduxFirebaseProvider, firebaseReducer } from 'react-redux-firebase'
import { createFirestoreInstance, firestoreReducer } from 'redux-firestore' // <- needed if using firestore

import Navigation from './Navigation/RootNavigator'

import PushComponent from './Utils/Functions/Notifications'

const fbConfig = {}

// react-redux-firebase config
const rrfConfig = {
  userProfile: 'users',
  useFirestoreForProfile: true // Firestore for Profile instead of Realtime DB
}

// Initialize firebase instance
RNFirebase.initializeApp(fbConfig)

// Initialize other services on firebase instance
RNFirebase.firestore() // <- needed if using firestore
RNFirebase.functions() // <- needed if using httpsCallable

// Add firebase to reducers
const rootReducer = combineReducers({
  firebase: firebaseReducer,
  firestore: firestoreReducer // <- needed if using firestore
})

// Create store with reducers and initial state
const initialState = {}
const store = createStore(rootReducer, initialState)

const rrfProps = {
  firebase: RNFirebase,
  config: rrfConfig,
  dispatch: store.dispatch,
  createFirestoreInstance // <- needed if using firestore
}
function App() {
  return (
    <Provider store={store}>
      <ReactReduxFirebaseProvider {...rrfProps}>
        <Navigation />
        <PushComponent />
      </ReactReduxFirebaseProvider>
    </Provider>
  );
}
export default App
```

I search but cannot found any solution. 
Does this make sense for you?
Am I missing something ?

Thanks guys

**Comment by prescottprue** [comment] 2020-01-10 18:59
Duplicate of [240 in redux-firestore](https://github.com/prescottprue/redux-firestore/issues/240)

There are some solutions discussed in that thread but the basic jist is that react-native-firebase changed how their library works internally (now uses Object.freeze). This will require an overhaul of the internals of react-redux-firebase and redux-firestore to use `extendApp` as done in in [this PR](https://github.com/prescottprue/react-redux-firebase/pull/792). It is a pretty major change, so it will most likely happen in the next major version.

**Comment by Cchumi** [comment] 2020-01-11 08:38
@prescottprue thanks a lot for your answer. 
I have this new react project to get the new query parameter like array-contains-any and in. 
Indeed this test is before merging to a production app. So I will wait for your library update. 

Thank you again. 

Cchumi

**Comment by prescottprue** [comment] 2020-01-29 05:10
Please follow #777 for updates on changing to support `Object.freeze` by switching to `extendApp` instead of extending the Firebase object

**Closed by prescottprue** 2020-01-29 05:10 UTC
