### ISSUE TITLE
firestoreConnect not updating when inserting new document

### ISSUE THREAD

**Issue by premitius** [prescottprue/react-redux-firebase#578] opened 2018-11-29 11:32 UTC
**What is the current behavior?**

Inserting a new document to a Firestore subcollection does not update the Firestore data with the added document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Using firestoreConnect to get user data and subcollections of a user:

```js
firestoreConnect(props => [
 `users/${props.userId}`,
 `users/${props.userId}/subcollection1`,
 `users/${props.userId}/subcollection2`,
]);
```
If inserting a new user, and then inserting a document to a subcollection, if the collection does not exist, and you add a document to a subcollection using `collection('subcollection1').add({...data})`, the `data` is inserted into Firestore, but the component using `firestoreConnect` does not receive the added document. `subcollection1` is null. 

Manually calling ``firestore.get(`users/${userId}/subcollection1`)`` after insert updates the data in the component.

**What is the expected behavior?**

The inserted document should be reflected in `firestore.data`

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Have not tried in earlier versions, currently using:
react-redux-firebase 2.1.8
redux-firestore 0.5.8

**Comment by prescottprue** [comment] 2018-11-30 00:22
@premitius How are you connecting to state for the component (i.e. where is the `connect` in comparison to the `firestoreConnect`, and what is the connect logic)? I would be interested to replicate directly, but it may be an issue that was already fixed on a soon to be released version of `redux-firestore`.

There is `0.6.0`, but without more info I can't be positive that this issue will be addressed by updating.

**Comment by GuyWithCookies** [comment] 2018-12-05 00:16
I can confirm the bug. I used the following code to update the firestore. The local redux store wouldn't update without the highlighted manual get call.
```
import React from 'react';
import { Container } from 'native-base';
import PropTypes from 'prop-types';
import { GiftedChat } from 'react-native-gifted-chat';
import { compose } from 'redux';
import connect from 'react-redux/es/connect/connect';
import { CONVERSATION_COLLECTION } from 'shared-modules/config';
import { withFirestore } from 'react-redux-firebase';
import NavigationHeader from '../../components/NavigationHeader';

/**
 * Chat Screen
 */
class Chat extends React.Component {
    static propTypes = {
        conversation: PropTypes.object.isRequired,
        firestore: PropTypes.object.isRequired
    };

    onSend(messages = []) {
        const { firestore, conversation } = this.props;
        console.log(messages);
        firestore
            .update(
                { collection: CONVERSATION_COLLECTION, doc: conversation.id },
                {
                    messages: [
                        ...(conversation.messages || []),
                        ...messages
                    ]
                },
            )
            .then(
                () => {
                    // FIXME: Manual get call to trigger the update
                    firestore.get(CONVERSATION_COLLECTION + '/' + conversation.id);
                },
                (err) => {
                    console.log(err);
                 },
            );
    }

    render() {
        const { conversation } = this.props;

        return (
            <Container testID="Screen:Chat">
                <NavigationHeader
                    headerText="Chat"
                />
                <GiftedChat
                    messages={conversation.messages.sort((a,b) => {
                        return -(a.createdAt - b.createdAt);
                    })}
                    alwaysShowSend
                    isAnimated
                    onSend={(messages) => this.onSend(messages)}
                />
            </Container>
        );
    }
}


export default compose(
    withFirestore,
    connect((state, ownProps) => {
            const conversationID = ownProps.navigation.getParam('conversationID', undefined);

            return {
                loading: state.firestore.status.requesting[CONVERSATION_COLLECTION] || false,
                conversation: {
                    id: conversationID,
                    ...state.firestore.data[CONVERSATION_COLLECTION][conversationID]
                },
                auth: state.firebase.auth
            };
        }
    )
)(Chat);

**Comment by prescottprue** [comment] 2018-12-05 03:29
@GuyWithCookies Good to know. Have you tried out `0.6.0` or `next` at all?

**Comment by GuyWithCookies** [comment] 2018-12-05 13:42
Perdon, I somehow must have missed the new version. I tried it now but apparently the version change introduces an error in the application:

![image](https://user-images.githubusercontent.com/17498736/49517099-99473480-f89b-11e8-8c28-9474e03a8fe8.png)

I use the same code as above - with `0.6.0` it breaks - with `0.5.8` it works (except of the bug discussed in this issue - of course). 

Is this a bug (I'll open a new issue for this then) or is there a breaking change between these versions of which I am not aware of?

**Comment by prescottprue** [comment] 2018-12-05 22:39
@GuyWithCookies It does seems like something we should open in a new issue. It appears to relate to `redux-persist` since I see `PersistGate` in the stack (although I'm not sure).

I would be interested to hear if this new error remains without `redux-persist`, but either way I would like to address both.

**Comment by prescottprue** [comment] 2019-02-08 19:39
Though these symptoms include redux-persist, I believe it is a similar issue to [121 of redux-firestore](https://github.com/prescottprue/redux-firestore/issues/121). Since it is a redux-firestore issue, going to move communication about it to that issue. Thanks for reporting.

**Closed by prescottprue** 2019-02-08 19:39 UTC
Labels: needs-repro
