### ISSUE TITLE
Add typings for Typescript

### ISSUE THREAD

**Issue by dotcs** [prescottprue/react-redux-firebase#142] opened 2017-05-24 12:12 UTC
Currently no typings for Typescript are available, are there any plans to add them? I found no information regarding Typescript support.

Right now using Typescript (with `noImplicitAny` option activated) it's only possible to require the package like so

```typescript
const reactReduxFirebase = require('react-redux-firebase');
const { firebaseConnect, isLoaded, isEmpty, dataToJS, pathToJS } = reactReduxFirebase;
```

Because typings are missing the development experience is not as good as it could be in a Typescript environment. [This intro](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) shows how to add them and why they are useful.

Additional info:
```
$ npm info @types/react-redux-firebase
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node@6/6.10.3/bin/node" "/usr/local/bin/npm" "info" "@types/react-redux-firebase"
npm ERR! node v6.10.3
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/@types%2freact-redux-firebase
npm ERR! 404
npm ERR! 404  '@types/react-redux-firebase' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dotcs/.npm/_logs/2017-05-24T11_04_33_311Z-debug.log
```

**Comment by prescottprue** [comment] 2017-05-24 15:28
There has currently been no plan to add them (no devs have asked yet).

Now that you have mentioned the need, I will look into adding this to the roadmap. Always open to pull requests if you wanted to start to add the functionality.

**Comment by prescottprue** [comment] 2017-05-31 07:41
[`v1.5.0-beta`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-beta) was released with initial typescript typings.

It was my first time playing with typescript, so let me know if it works for you.

**Comment by prescottprue** [comment] 2017-06-05 15:40
@dotcs Let me know if you get a chance to try out the typings. Otherwise, going to include this in the upcoming `v1.5.0` release.

**Comment by dotcs** [comment] 2017-06-05 16:45
@prescottprue Sorry for the late answer. And many thanks for addressing the issue. I have tested it with version `v.1.5.0-beta`, but although the `index.d.ts` is specified in the `package.json`, it's missing in the release. 

The current tree of the release looks like this:

```
/Users/fmueller/Library/Caches/Yarn/v1/npm-react-redux-firebase-1.5.0-beta-cca139de1022c1e203ae6078b48a7cbf3c701931/
├── CHANGELOG.md
├── LICENSE.md
├── README.md
├── dist
│   ├── react-redux-firebase.js
│   └── react-redux-firebase.min.js
├── es
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── lib
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── package.json
└── src
    ├── actions
    │   ├── auth.js
    │   ├── index.js
    │   ├── query.js
    │   └── storage.js
    ├── compose.js
    ├── connect.js
    ├── constants.js
    ├── helpers.js
    ├── index.js
    ├── reducer.js
    └── utils
        ├── actions.js
        ├── auth.js
        ├── events.js
        ├── index.js
        ├── populate.js
        ├── query.js
        └── storage.js

10 directories, 57 files
```

I've manually copied it over from [here](https://raw.githubusercontent.com/prescottprue/react-redux-firebase/v1.5.0/index.d.ts). After copying the file things work out smoothly, although the definitions contain lots of `any` statements, which could be improved. But of course this can be done iteratively in the future.

Given the manually copied `index.d.ts` file, my import statements now look like this

```javascript
import { firebaseConnect, isLoaded, isEmpty, dataToJS, pathToJS } from 'react-redux-firebase';
```
which is awesome! 👍 

So from my perspective it's fine to include it in the next release if you make sure that the `index.d.ts` is distributed along with the package.

Thanks again for addressing the issue so quickly. :)

**Comment by prescottprue** [comment] 2017-06-05 17:21
Great catch! Will make sure that is included in the release.

**Comment by prescottprue** [comment] 2017-06-06 04:33
@dotcs [`v1.5.0-beta.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-beta.2) was released with the typescript typings included in the files list. Let me know if you get a chance to try it out.

**Comment by dotcs** [comment] 2017-06-06 09:22
@prescottprue Thanks for the update. Unfortunately the `index.d.ts` is still not included. Are you sure that the file is not ignored somehow when building the NPM module?

```
/Users/dotcs/Library/Caches/Yarn/v1/npm-react-redux-firebase-1.5.0-beta.2-b97616ef610459a3427c0588f7db5da69d87223b/
├── CHANGELOG.md
├── LICENSE.md
├── README.md
├── dist
│   ├── react-redux-firebase.js
│   └── react-redux-firebase.min.js
├── es
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── lib
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── package.json
└── src
    ├── actions
    │   ├── auth.js
    │   ├── index.js
    │   ├── query.js
    │   └── storage.js
    ├── compose.js
    ├── connect.js
    ├── constants.js
    ├── helpers.js
    ├── index.js
    ├── reducer.js
    └── utils
        ├── actions.js
        ├── auth.js
        ├── events.js
        ├── index.js
        ├── populate.js
        ├── query.js
        └── storage.js

10 directories, 57 files

```

**Comment by prescottprue** [comment] 2017-06-06 19:49
@dotcs You are right! Looks like beta 3 has it in there.

It ended up being solved by removing the `filesMap` and `files` fields from the package file. I had a chance to test it out with the published version, and it seems to be working.

Mind trying it again and letting me know?

**Comment by dotcs** [comment] 2017-06-06 20:07
@prescottprue You're right, it's there right now. Awesome! Thanks for your sustained effort. 👍 

```
/Users/fmueller/Library/Caches/Yarn/v1/npm-react-redux-firebase-1.5.0-beta.3-9e5400a823c19988f85170ea035e9fac7ddd6571/
├── CHANGELOG.md
├── CNAME
├── CODE_OF_CONDUCT.md
├── LICENSE.md
├── PATRONS.md
├── README.md
├── SUMMARY.md
├── book.json
├── codecov.yml
├── dist
│   ├── react-redux-firebase.js
│   └── react-redux-firebase.min.js
├── es
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── index.d.ts
├── lib
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── package.json
├── src
│   ├── actions
│   │   ├── auth.js
│   │   ├── index.js
│   │   ├── query.js
│   │   └── storage.js
│   ├── compose.js
│   ├── connect.js
│   ├── constants.js
│   ├── helpers.js
│   ├── index.js
│   ├── reducer.js
│   └── utils
│       ├── actions.js
│       ├── auth.js
│       ├── events.js
│       ├── index.js
│       ├── populate.js
│       ├── query.js
│       └── storage.js
├── webpack.config.js
└── yarn.lock

10 directories, 66 files

```

**Closed** 2017-06-21 05:14 UTC
Labels: enhancement, in-pre-release

**Comment by pvdyck** [comment] 2017-06-26 11:47
Looks like the npmFileMap change did not make it ? (in version 2 I mean)

**Comment by prescottprue** [comment] 2017-06-26 19:06
@pvdyck The `npmFileMap` is no longer being used as part of this change (which is included in `v2.0.0`).

I also confirmed that the typescript typings are released with the `v2.0.0` versions (and they appear to be). Are you not able to use them?

**Comment by maxyharr** [comment] 2017-07-18 04:45
`Argument of type 'typeof firebase' is not assignable to parameter of type 'ConfigObject'.`

I'm getting this when I try to pass the firebase configured object directly instead of the config object like so...

```
import * as firebase from 'firebase'
const config = {etc...}
firebase.initializeApp(config)
const storeWithFirebase = compose(
    reactReduxFirebase(
        firebase,  // [ts] Argument of type 'typeof firebase' is not assignable to parameter of type 'ConfigObject'.
        etc...
```

Is there any chance of adding this?

**Comment by prescottprue** [comment] 2017-07-18 06:23
@maxyharr Is that in `v2.0.0` that you are running?

It may be that the typescript typings need a small update for `v2.0.0`.

**Comment by maxyharr** [comment] 2017-07-18 15:50
@prescottprue yeah that's 2.0.0. I think you're right. I think it just needs a small tweak.

**Comment by prescottprue** [comment] 2017-07-20 02:02
[v2.0.0 Beta 3 was released ](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.3) with some updates to the typings for v2 syntax.

@maxyharr If it does not work as expected for v2 after this pre-release, could you open another issue?
