### ISSUE TITLE
getFirestore for redux thunk

### ISSUE THREAD

**Issue by E-RROR** [prescottprue/react-redux-firebase#1043] opened 2020-12-15 19:38 UTC
Hello, How can i use getFirestore instead getFirebase in redux thunk for version 3, i don't see any documentation for that

**Comment by prescottprue** [comment] 2020-12-27 18:08
Thanks for reaching out. Closing as a duplicate of https://github.com/prescottprue/react-redux-firebase/issues/839 so we keep all of the info in one place - there is a proposed solution, but haven't tried it myself yet

**Closed by prescottprue** 2020-12-27 18:08 UTC
