### ISSUE TITLE
bug(populate): isLoaded returns true when populated children are still loading

### ISSUE THREAD

**Issue by marekolszewski** [prescottprue/react-redux-firebase#121] opened 2017-05-04 00:19 UTC
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
For populated queries, isLoaded returns true when the base query completes, even if the populated child queries are still outstanding.

**What is the expected behavior?**
Ideally it would return false while the populated children are being loaded. For backwards compatibility, it may make sense for isLoaded to take an extra parameter such as 'waitForPopulate'.

**Comment by prescottprue** [comment] 2017-05-04 01:02
@marekolszewski This is indeed expected behavior, and if you are seeing it, it is for sure a bug.

Which version are you using? Can you possibly provide a repo where the bug can be reproduced?

Feel free to message me [directly on gitter](https://gitter.im/redux-firebase/Lobby) instead if the repo is private.

**Comment by prescottprue** [comment] 2017-05-05 01:18
@marekolszewski I was able to replicate. It seems that [due to the order of dispatches](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/query.js#L137-L155), there could be a split second before the other actions are dispatched (even though all of the data has been retrieved from Firebase already).

Going to experiment with switching the order of these and see if that helps. The goal being that the main data (what will be used as the path within `populatedDataToJS`) is updated last, meaning that all of the other data needed for population will already be in redux.

Will keep this issue updated with progress.

**Comment by marekolszewski** [comment] 2017-05-05 01:51
@prescottprue Sounds good! 

For anyone else encountering this issue, a simple workaround is to just do a typeof on the field being populated and waiting until it becomes an object.

**Comment by marekolszewski** [comment] 2017-05-05 02:00
@prescottprue BTW, I also just noticed that adding type: 'once' to my queries is also breaking population for me. I wonder if it's related to this.

**Comment by prescottprue** [comment] 2017-05-05 02:15
@marekolszewski I don't believe it is related. Once does not currently support populate, but this should be added to the roadmap for sure.

I agree with type checking. It is how my team and I decided to work around it for now.

**Comment by prescottprue** [comment] 2017-05-05 08:04
I believe I may have a fix for this, and it should make it into `v1.4.0-rc.2`. Testing it a bit more, but will hopefully be ready for release tomorrow.

As mentioned in the roadmap, there are future plans for making this configurable.

**Comment by prescottprue** [comment] 2017-05-06 09:14
[`v1.4.0-rc.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-rc.2) includes the fix for this. I tested plenty, but if anyone else get a chance, post your results.

**Comment by prescottprue** [comment] 2017-05-17 23:04
[`v1.4.0` was released](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0) with this functionality included, so this is now out of pre-release.

**Closed by prescottprue** 2017-05-17 23:04 UTC
Labels: bug, in-pre-release

**Comment by marekolszewski** [comment] 2017-05-18 06:06
@prescottprue Awesome, thanks for fixing this!
