### ISSUE TITLE
Logout causes rejection error

### ISSUE THREAD

**Issue by jhefreyzz** [prescottprue/react-redux-firebase#838] opened 2020-01-19 09:08 UTC
**Do you want to request a *feature* or report a *bug*?**   bug

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

This issue relates to #529 which was closed.

**What is the current behavior?**
When a authenticated user logs out, it will also logout to same app open in other tab or windows. The behavior seems normal until a few seconds a rejection will be thrown.
`Unhandled Rejection (FirebaseError): Missing or insufficient permissions.`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
![issue](https://user-images.githubusercontent.com/20869829/72678083-857d8280-3add-11ea-8d2b-6449038f54e5.gif)

**What is the expected behavior?**
The app should not thrown this error (I'm not sure of it).

Security Rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```
Current config used:
```
const config = {
  userProfile: "users",
  useFirestoreForProfile: true, 
  enableLogging: false
};
```

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
OS: Windows 10
Browser: Brave Browser Version 1.2.43
Dependencies: All packages are in the latest version

**Comment by prescottprue** [comment] 2020-01-21 18:11
Do you attach any listeners on the page which is loaded? Did it show what path the auth error is for? Are any errors written to redux state?

Seems like it may be the profile listener?

Can you provide this logic in a repo, codesandbox, or other similar tool so I can make sure I am fully replicating on my end?

**Comment by prescottprue** [comment] 2020-01-21 18:16
After searching through the issues it seems https://github.com/prescottprue/react-redux-firebase/issues/508 may be related or even the same issue

**Comment by jhefreyzz** [comment] 2020-01-22 15:06
Hi @prescottprue sorry take too long to reply.
I've created a repo https://github.com/jhefreyzz/react-redux-firebase-demo to replicate the issue mentioned above.

**Comment by prescottprue** [comment] 2020-01-24 19:51
Fix [released in v3.1.0](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.1.0) - thanks to @illuminist for the PR!

**Closed by prescottprue** 2020-01-24 19:51 UTC

**Comment by abdulghanitech** [comment] 2020-09-03 13:22
I can confirm this issue in 3.6.0

**Comment by prescottprue** [comment] 2020-09-03 18:40
@abdulghanitech Thanks for reaching out. Please open a new issue with a full reproduction

**Comment by Tellefsonjr** [comment] 2020-11-29 09:53
I couldn't find any threads for my particular issue, but this thread kept coming up - my issue was not with the profile listener, but with firestoreConnect() not clearing out the listeners after firebase.logout() method. Thought I'd comment here if it helps anyone:

Changed from:
```
export default compose(  
    connect(mapStateToProps),  
    firestoreConnect((state) =>  ['collection', 'collection']), 
)(MyComponent)
```

Changed to:
```
export default compose(  
    connect(mapStateToProps),  
        firestoreConnect((state) => {  
            return state.auth.isLoaded && state.auth.uid ? ['collection', 'collection'] : []  
      }),  
 )(MyComponent)
```

Not sure if this is intended, but really wished the firestoreConnect docs listed how to handle the listeners after logout :(

**Comment by prescottprue** [comment] 2020-11-29 23:49
@Tellefsonjr What you have done is a good approach thanks for sharing - I have also seen that handled by only rendering the component which has the listeners if auth is attached [as seen in the state based query example snippet](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery)
