### ISSUE TITLE
Deps won't get installed

### ISSUE THREAD

**Issue by rzmz** [prescottprue/react-redux-firebase#179] opened 2017-07-01 20:15 UTC
I installed react-redux-firebase@next which resolved to version 2.0.0-alpha.5
I got an error when running my app: "TransformError: unkwnown plugin "add-module-exports" specified in myproject/node_modules/react-redux-firebase/.babelrc"
Looking into the myproject/node_modules/react-redux-firebase/node_modules revealed that it only contained firebase directory, not all the deps listed in your package.json file.
When I tried to manually run npm install there, I got the error:

> cross-env BABEL_ENV=commonjs NODE_ENV=development webpack src/index.js dist/react-redux-firebase.js

Hash: 45381c545b8497b35773
Version: webpack 2.6.1
Time: 49ms
                  Asset     Size  Chunks             Chunk Names
react-redux-firebase.js  3.33 kB       0  [emitted]  main
   [0] ./src/index.js 253 bytes {0} [built] [failed] [1 error]

ERROR in ./src/index.js
Module parse failed: /Users/rasmus/dev/Kola/node_modules/react-redux-firebase/src/index.js Unexpected token (21:2)
You may need an appropriate loader to handle this file type.
|   getFirebase,
|   helpers,
|   ...helpers
| }
|

**Comment by prescottprue** [comment] 2017-07-01 20:47
@rzmz I believe this is a duplicate of #175

**Comment by prescottprue** [comment] 2017-07-01 21:25
@rzmz What version of npm and node are you using? With newer versions of npm, `node_modules` are all flattened and placed on the top level (unless only used by that one dependency), so I am wondering if the dependencies are loading differently for some reason?

Can you see if any of the other dependencies are at the top level of your node_modules folder (such as `hoist-non-react-statics` or `jwt-decode`. If they are, that narrows it down to being an issue of correctly pointing to the dependencies.

**Comment by prescottprue** [comment] 2017-07-02 01:05
Just released [`v2.0.0-alpha.6`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-alpha.6) that has the `.babelrc` removed and also no longer uses `add-module-exports`.

The hope is that the issue was due to babel looking to the `.babelrc` file inside of the project.

**Closed** 2017-07-02 02:05 UTC
