### ISSUE TITLE
question(integrations): how to get firebase instance in v3.*.* since getFirebase() is deprecated

### ISSUE THREAD

**Issue by yorickreum** [prescottprue/react-redux-firebase#607] opened 2019-01-04 23:24 UTC
Since the change to the React context providers (more precisely: https://github.com/prescottprue/react-redux-firebase/pull/566) the getFirebase() is not available anymore. But how do we access our firebase instance from Redux store now, for example from inside of an action creator?

**Comment by prescottprue** [comment] 2019-01-06 20:15
@yorickreum I have been sticking to passing the instance from `props.firebase`. The current plan is to go expose a middleware and actionCreators so that you can just dispatch the action creators directly with your data. Since it isn't finished yet, I haven't written docs about it yet, but we can discuss more on Gitter. Interested to hear your thoughts!

**Comment by yorickreum** [comment] 2019-01-06 20:37
Sounds good!

Exposing a middleware for thunk would be the same approach as getFirebase() was?

In my particular case I wanted to sign up and send a verification mail directly afterwards. Because I didn't see an actionCreator for sending a verification mail I started to write an own actionCreator, but saw no possibility to access our getFirebase instance... Passing it from the props could be a workaround.

**Comment by prescottprue** [comment] 2019-01-06 23:37
The goal for the middleware is for it to be even more simple that `getFirebase` and expose sync action creators for everything instead of wrapped async methods.

All of that aside, `auth` is exposed so you can call all of the methods directly. The methods that are exposed are wrapped in dispatch since most of them update state, since you don't necessarily need a state update, you can just do a handler [similar to in the material example](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/material/src/routes/Signup/components/SignupPage/SignupPage.enhancer.js#L23-L29):

```js
import { compose } from 'redux'
import { withHandlers } from 'recompose'
import { withFirebase } from 'react-redux-firebase'

compose(
  withFirebase
  withHandlers(
    signupAndEmail: (props) => creds =>
      props.firebase
        .createUser(creds, {
          email: creds.email,
          username: creds.username
        })
        .then(firebase.auth().currentUser.sendEmailVerification)
        .then(() => {
          console.log("Signup and email verification successful:")
        })
        .catch(err => {
          console.error("error with signup:", err)
        })
  )
)
```

**Comment by idanlo** [comment] 2019-01-25 21:20
any update on this? I want to still have access to firebase instance but use `firestoreConnect` which I cannot because I use react-redux v6

**Comment by prescottprue** [comment] 2019-02-08 19:19
@idanlo The version of `react-redux-firebase` available on the `next` branch has support for react-redux v6 [as mentioned in the installation section of the README](https://github.com/prescottprue/react-redux-firebase#installation). That said, I think there is still an open question of the best way to access the instance within separate actions/middlewares/flows such as thunks/sagas or redux-observable.

Directing #617 here as well since I believe it is a similar question.

For now, I personally have been accessing the instance from props and passing it as necessary (even to separate sagas/thunks if necessary instead of having it passed as part of setup).

**Comment by prescottprue** [comment] 2019-02-28 19:04
This is also a duplicate of #635, so going to close this and make future updates there. Thanks to everyone for reaching out with thoughts!

**Closed by prescottprue** 2019-02-28 19:04 UTC
Labels: discussion, examples, question
