### ISSUE TITLE
bug(populates): populates clears all data at root

### ISSUE THREAD

**Issue by Domiii** [prescottprue/react-redux-firebase#130] opened 2017-05-13 07:14 UTC
The following query causes all other data currently stored at `users` (which is the `root`) to be deleted. As soon as the `populates` portion is resolved, all my (self-managed) users are gone from my client (however the `users` path is still in the `firebaseConnect` mix):

```js
populates: [
  { child: 'uid', root: 'users', keyProp: 'uid' }
]
```

**UPDATE**

At some point, [this SET action](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/query.js#L146-L153) is dispatched with `path` = `users`:

```js
dispatch({
  type: SET,
  path,
  data: result,
  timestamp: Date.now(),
  requesting: false,
  requested: true
})
```

From the looks of it, that is because [promisesForPopulate](https://github.com/prescottprue/react-redux-firebase/blob/master/src/utils/populate.js#L112) actually creates a big object with all the `user` children which then overrides all previous data at `root` (= `/users`), using the above `SET` action.

### Possible Fix (1)

Each fetched result object should be set with it's own `SET` action. So instead of:

```js
SET('/users', {
  uid1: {...},
  uid2: {...}
});
```

you get:

```js
SET('/users/uid1', {...});
SET('/users/uid2', {...});
```

### Possible Fix (2)

Add an `ADD` or `UPDATE` action which adds to rather than overrides the given data at the given `root` path:

```js
ADD('/users', {
  uid1: {...},
  uid2: {...}
});
```

**Comment by prescottprue** [comment] 2017-05-13 16:44
Have you tried using storeAs for your other users query?

**Comment by Domiii** [comment] 2017-05-13 17:37
Thanks! I'll try that as a work-around.

When do you think `populate` will be fixed though?

**Comment by prescottprue** [comment] 2017-05-14 15:00
@Domiii placing the populate results in a different place in redux would also require modifying `populatedDataToJS`. Data is placed  into redux under its root.

**Comment by Domiii** [comment] 2017-05-20 07:57
I tried to give it a swing, but `NPM` bugs keep holding me back.

I added my own fork of `react-redux-firebase` as a local git submodule which is a bit of a pain (see below).

### PS: (For those who are interested) How to set this up as an NPM submodule?

NOTE: I know this does not technically belong into this thread. If you don't need/want it, I'll delete it.

WARNING #1: Git does not make it easy to remove or change submodules, gotta move through a few steps there, but you can google that easily.

WARNING #2: NPM does not handle local sub modules well. Here is how I got it to work:

1. Follow [this article](https://medium.com/@arnaudrinquin/build-modular-application-with-npm-local-modules-dfc5ff047bcc) to setup your git submodule and add it to `package.json`
1. `git submodule update --init --recursive`
1. `cd local_modules/react-redux-firebase`
1. `npm install`
1. `cd ../..`
1. `npm update`

FYI: [This NPM  bug](https://github.com/npm/npm/issues/9707) explains how NPM neglects to install dev-dependencies before building for local submodules. I even had to run `npm install` from the submodule directory entirely to get all packages installed. If I don't, it keeps complaining that the `jwt-decode` package is missing. Congrats: You now have a second `node_modules` folder in your submodule which is entirely useless, but that's how things go :/

**Comment by prescottprue** [comment] 2017-05-20 20:26
You shouldn't necessarily need to make this a submodule. If you are developing locally you should be able to npm link.

It will take more of a code change than transforming that one line. `v1.5.0-alpha` should include this functionality.

**Comment by Domiii** [comment] 2017-06-04 15:50
Good news! I finally came around to it!

Bad news: `storeAs` can only be set once for the query, and it does not really seem to be integrated with how `populates` pulls in child data.

In fact, `storeAs` is not passed to promisesForPopulate, as you can see in [this line](https://github.com/prescottprue/react-redux-firebase/blob/v1.5.0/src/actions/query.js#L136):

```js
promisesForPopulate(firebase, dataKey, data, populates)
```

Hence, `path` in the following `forEach` loop is still equal to `root`, for every entry in the `populates` array:

```js
forEach(results, (result, path) => {
  dispatch({
    type: SET,
    path,
    data: result,
    timestamp: Date.now(),
    requesting: false,
    requested: true
  })
})
```

**Comment by Domiii** [comment] 2017-06-04 16:15
I have also found out why it is buggy in the first place:

The `SET` reducer just overrides all data at path, when new data comes in, and if I'm not mistaken, populated child data never gets deleted from the state, just letting it dangle in there for all eternity.

What should happen instead, is:

1. `SET` should merge data. Or a new `MERGE` action needs to be defined for the default case, where data should be merged in, rather than deleted.
1. `UNSET_LISTENER` should not remove data when the path of the corresponding query is a subpath of any still active path.
1. `UNSET_LISTENER` should respect `populates` settings, to also remove all currently cached children related to the corresponding query in the same way (with respect to all active paths).
1. That implies that we would have to maintain a set of all currently active paths (which would include `populates` paths.


While this is quite a bit of work, this would actually allow a lot more than just above `populates` query to work:

1. This way, when a `@firebaseConnect`ed component gets unmounted, all it's data is cleanly removed, and:
1. We can have `@firebaseConnect` paths be subsets of one another without subscribed data suddenly vanishing.


On the plus side: I don't think, we have to make any changes to `populatedDataToJS` :)

**Comment by prescottprue** [comment] 2017-06-05 03:59
@Domiii Great input. Going to look into this a bit more. It would be nice to come up with a way to enable/disable this through config so that it remains backwards compatible (that way it can be done for a `v1.*` version).

**Comment by prescottprue** [comment] 2017-07-12 02:12
#192 posed and is a duplicate of this issue (noting just to keep track)

@Domiii Would be interested to see what you think of `v2.0.0` with respect to sharing data from different queries (like you were mentioning above). Also, the listeners are tracked in state, so keeping an eye on which components set which listeners is much easier.

**Comment by Domiii** [comment] 2017-08-10 11:51
Seeing how my workarounds are running out of juice, I feel more and more compelled dedicating some time to this, even though I basically have negative time to work on this...

Did anything else happen in the meantime that would conflict with this plan, or can I go ahead on this (if I can find the time in the next two weeks)?

**Comment by prescottprue** [comment] 2017-08-10 17:45
@Domiii This would be awesome.

With v2 listeners are tracked in state already, which could make this quite bit easier. Other than that, this shouldn't be affected by too much that has happened recently.

If you are trying to add it to v2, then go with the `v2.0.0` branch, but if you are adding it to v1, go with the `v1.5.0` branch.

**Comment by prescottprue** [comment] 2017-09-02 09:15
@Domiii [`v2.0.0-beta.8`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.8) support for this (thanks for the help @marekolszewski) through the `MERGE` action.

**Closed by prescottprue** 2017-09-02 09:15 UTC
Labels: bug

**Comment by Domiii** [comment] 2017-09-02 14:28
That is truly awesome! Looking forward to the final version actually not overriding data or removing data when subscribing to supersets and subsets of data across different containers! :D

(sorry, I did not end up finding/allocating the time myself :/)
