### ISSUE TITLE
bug(docs): cannot access useFirestoreConnect in documentation.

### ISSUE THREAD

**Issue by harish-aka-shivi** [prescottprue/react-redux-firebase#817] opened 2019-12-30 13:42 UTC
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When going through the documentation, I cannot access the useFirestoreConnect. It is just not selecting the useFirestoreConnect Menu.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
It is happening randomly. Earlier the link to Github repo in the header stopped working.

![redux-firebase-2](https://user-images.githubusercontent.com/13154441/71584314-1644ec00-2b38-11ea-8d33-301bb6012bfc.gif)

**What is the expected behavior?**
It should go to useFirestoreConnect page and select the appropriate item in the left sidebar.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Version: Current version
Browser: Firefox
OS: macOS

**Comment by TimRotich** [comment] 2020-01-25 10:01
Am trying to connect to Firebase authentication but anytime i try to register a new user via the android app i get the message saying invalid api key,please pass a valid api key.... kindly help

**Comment by harish-aka-shivi** [comment] 2020-01-26 05:13
Please check that the key that you are trying to pass is valid? Also, if you need help more synchronously, you can ask the question on the [gitter](https://gitter.im/redux-firebase/Lobby) community:

**Comment by prescottprue** [comment] 2020-01-27 18:23
@TimRotich please open a new issue with steps to reproduce your issue since it does not seem related to this broken docs link. My guess is that you are not passing a valid API key since that is what the error is saying, but impossible to know without more context

**Comment by prescottprue** [comment] 2020-01-29 04:59
Fixed in recent update. @TimRotich please feel free to open a new issue describing the problem you are having

**Closed by prescottprue** 2020-01-29 04:59 UTC
Labels: bug, docs-update
