### ISSUE TITLE
bug(docs): auth section of v3.0 docs still contains v2.0 code

### ISSUE THREAD

**Issue by Akash187** [prescottprue/react-redux-firebase#676] opened 2019-04-11 07:55 UTC
I just went through the documentation of react-redux-firebase and found that code in auth section (Wait For Auth To Be Ready) of v3.0 is not up to date actually contain v2.0 code if you compare it with the migration guide for v2 to v3.

Please consider updating it.

**Comment by prescottprue** [comment] 2019-04-18 06:16
@Akash187 I was not aware of this, it must have slipped through. Thanks for reporting!

**Comment by Akash187** [comment] 2019-04-18 06:27
@prescottprue Happy to Help. You may close this thread if bug is fixed.

**Comment by WhoIsDT** [comment] 2019-05-04 13:11
Can you please help to repair store.firebaseAuthIsReady in 3.0 version? My app using this method but after update everything broke:(

**Comment by prescottprue** [comment] 2019-05-04 18:25
@WhoIsDT there is a bunch of discussion about that in [this issue](https://github.com/prescottprue/react-redux-firebase/issues/635). Would be interested to hear your use case about why it is folks find it necessary to have things on the store - the new context API changes how things are done, so there isn't the instance on the store anymore. `firebaseAuthIsReady` was intended for SSR, and so that bootup time of your app isn't long, it is suggested that you [connect to auth from state and wait for it to load](http://react-redux-firebase.com/docs/recipes/auth.html#wait-for-auth-to-load)

**Comment by prescottprue** [comment] 2019-07-13 07:29
Fixed in [v3.0.0-alpha.13 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.0.0-alpha.13). Thanks for reporting!

**Closed by prescottprue** 2019-07-13 07:29 UTC
Labels: bug
