### ISSUE TITLE
Firebase state incompatible with serializable-state-invariant-middleware from @reduxjs/toolkit

### ISSUE THREAD

**Issue by matchatype** [prescottprue/react-redux-firebase#854] opened 2020-01-30 21:46 UTC
I'm using [@reduxjs/toolkit](https://redux-starter-kit.js.org/) which is pretty awesome. However, one of the cool middleware loaded in development, [serializable-state-invariant-middleware](https://redux-starter-kit.js.org/api/other-exports#createserializablestateinvariantmiddleware) complains about a couple of keys not being serializable:

```
A non-serializable value was detected in an action, in the path: `auth`...
A non-serializable value was detected in an action, in the path: `profile.token`...
A non-serializable value was detected in an action, in the path: `firebase.profile.token`...
```

This happens once authenticated, with auth loaded in state. I suppose there's not a lot to do here, since we actually want `auth` to be in state, however the errors in console are quite annoying. The middleware can be actually configured to pass an array of dot-separated path strings to ignore when checking for serializability, but I was able to ignore only the third path successfully.

```
const configureAppStore = (preloadedState = initialState) => {
  return configureStore({
    middleware: [
      ...getDefaultMiddleware({
        thunk: {
          extraArgument: {getFirebase, getFirestore},
        },
        serializableCheck: {
          ignoredPaths: ['auth', 'profile.token', 'firebase.profile.token'],
        },
      }),
    ],
    reducer: rootReducer,
    preloadedState,
  })
}
```

Is the configuration wrong? Is there a better way to achieve this while still keeping the benefit of the middleware?

**Comment by prescottprue** [comment] 2020-01-31 02:08
I believe this is a duplicate of #761 - no current way that I am aware of to config other than what you are describing

**Closed** 2020-01-31 02:08 UTC
