### ISSUE TITLE
Error: Cannot find module './factoryWithThrowingShims' from '/app/node_modules/react-redux-firebase/dist'

### ISSUE THREAD

**Issue by karltaylor** [prescottprue/react-redux-firebase#128] opened 2017-05-10 19:14 UTC
Just did a fresh npm install on a new project and imported into my project and got 

```javascript
Error: Cannot find module './factoryWithThrowingShims' from '/app/node_modules/react-redux-firebase/dist'
    at /app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by prescottprue** [comment] 2017-05-10 19:29
What version did you npm install? You can check using `npm ls react-redux-firebase`.

Also, what did you specify in your `package.json` for version. What is your loader config look like if you are using webpack?

**Comment by DavidBrear** [comment] 2017-05-11 22:19
getting this with 
`react-redux-firebase@1.4.0-rc.2`
Although i'm also using: `react@16.0.0-alpha.6`

**Comment by prescottprue** [comment] 2017-05-11 22:26
Interesting thought @DavidBrear.

Have you tried older versions of react-redux-firebase (i.e. `v1.3.4`)? Usage of `prop-types` within react-redux-firebase didn't start until `v1.4.0-rc.1`.

Have you tried a v15 version of `react` like `15.5.4` (latest) or `v15.3.2` (used in all of the `react-redux-firebase` examples)?

**Comment by DavidBrear** [comment] 2017-05-12 11:49
Moving to `v1.4.0-rc.1` fixed it. I've pulled down the source to see if I could make a PR to fix in `rc.2` will try to get to it today.

**Comment by prescottprue** [comment] 2017-05-12 18:44
@DavidBrear That would be great. This is one of the last things to get ironed out before the `v1.4.0` release.

If we can't get it ironed out, we might have to go back to not using `prop-types` (which will throw deprecation warnings for some)

**Comment by prescottprue** [comment] 2017-05-16 19:04
[`v1.4.0-rc.3`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-rc.3) has been released. It includes switching back to importing PropTypes from `react` instead of `prop-types` (which has been moved to [`1.5.0` within the roadmap](http://react-redux-firebase.com/docs/roadmap.html#next-minor-version-v150))

@DavidBrear This means you should be able to use `v1.4.0-rc.3`, let me know if you get a chance to check it out. If so, planning on releasing `v1.4.0` from rc.3.

**Note**: Issue remaining open until this is out of pre-release

**Comment by prescottprue** [comment] 2017-05-17 23:03
[`v1.4.0` has been released](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0) so this is now out of pre-relase. `prop-types` usage has been [moved out to `v1.5.0`](http://react-redux-firebase.com/docs/roadmap.html#next-minor-version-v150).

**Comment by miketamis** [comment] 2017-05-24 04:55
Im still getting this error:

```
Building JavaScript bundle: error
Unable to resolve module `./factoryWithThrowingShims` from `/node_modules/react-redux-firebase/dist/react-redux-firebase.js`: Directory /node_modules/react-redux-firebase/dist/factoryWithThrowingShims doesn't exist
```

my version  react-redux-firebase@1.5.0-alpha

**Comment by prescottprue** [comment] 2017-05-24 06:31
@miketamis What is your webpack config? Are you using webpack 1 or 2?

Can anyone provide a repo where this can be reproduced?

**Comment by prescottprue** [comment] 2017-05-24 07:36
Another theory:

It may have to due with `prop-types` needing to be set as an external in the webpack config. This would make it so that `prop-types` points to the one required by your project instead of being included in the bundle (means that `prop-types` will instead of a peer dependency instead of dependency).

**Comment by ricardokdz** [comment] 2017-05-24 23:02
i have the same problem using react and react native

**Comment by miketamis** [comment] 2017-05-24 23:26
Yeap this error for me was with Expo. I fix it by putting the proptype repo into the react-redux-firebase dist folder in node_modules (obviously not a good fix)

**Comment by prescottprue** [comment] 2017-05-25 01:05
@ricardokdz and @miketamis ok, going to try some stuff and hopefully get a alpha.2 version out later tonight that address this

**Comment by ricardokdz** [comment] 2017-05-25 06:53
@miketamis Does not work for me. How's your directory structure?

**Comment by prescottprue** [comment] 2017-05-25 14:51
@ricardokdz The directory structure shouldn't be causing any issues. I have been using both the material example and the react-native examples to test.

Can you provide a repo that you are working on to reproduce the issue? For now I am just having to guess at things that might fix the issue.

**Comment by prescottprue** [comment] 2017-05-26 22:29
@ricardokdz @miketamis @karltaylor What version of webpack are you using? Can you possibly post your webpack.config? If using webpack 2, how do your webpack configs compare to [the webpack2 example](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/snippets/webpack2/webpack.config.js)?

I am able to use `v1.5.0-alpha` with both webpack 1 and 2 with no issues.

##### browser field

It has come to my attention though that more often that not (seems like it is happening in your case) bundling libraries end up using the `browser` field of `package.json` if it is defined. In the case of react-redux-firebase, that points to the bundled/webpacked version (which may not be what you want if you are also using webpack).

If we can confirm that this is what is happening, I can release `1.5.0-alpha.2` with the only change being removal of the `browser` field from the package file. That way, only the module version can be loaded (shouldn't cause dependency errors since it is not bundled).

**Comment by prescottprue** [comment] 2017-05-30 21:24
[`v.1.5.0-alpha.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-alpha.2) was released without the `browser` field within `package.json`. This means that webpack should no longer point to the bundle (but instead the es5ified version).

@ricardokdz @miketamis and @karltaylor Please let me know if any of you get a chance to try this out or can provide a repository where I can reproduce the issue so the fix can be confirmed.

**Comment by prescottprue** [comment] 2017-05-31 07:43
[`v1.5.0-beta`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-beta) also does not include the `browser` field, so it should respond the same way.

**Closed** 2017-06-21 04:31 UTC
Labels: in-pre-release, on-roadmap

**Comment by stevematdavies** [comment] 2017-10-20 18:14
I have the same error, im using react-dom 16 and no other library

**Comment by prescottprue** [comment] 2017-10-20 18:40
@stevematdavies This issue is from a while back and should be solved by being up to date. A few questions would help me get to the bottm of it faster:

* What version of `react-redux-firebase` are you using?
* What does your `.babelrc` look like?
* Are you npm linking?
* What does your webpack/rollup config look like? (or your build setup if not using one of these)
* Have you tried any of the examples or `generator-react-firebase`?

**Comment by imdragonet** [comment] 2018-01-12 09:58
https://webpack.js.org/configuration/externals/

try add prop-types library to external field.

**Comment by prescottprue** [comment] 2018-01-12 10:07
@imdragonet Do you mean within `react-redux-firebase` or in an application using it?

From what I thought (could be totally wrong), it was supposed to be a dependency handled by any library using it instead of a peer dependency. Open to doing that though if it some are still seeing this issue.

**Comment by UbaidAhemdAwan** [comment] 2018-07-11 09:06
Can anyone help me on this?

error: bundling failed: Error: Unable to resolve module `./factoryWithThrowingShims` from `/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/index.development.js`: The module `./factoryWithThrowingShims` could not be found from `/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/index.development.js`. Indeed, none of these files exist:

  * `/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/factoryWithThrowingShims(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/factoryWithThrowingShims/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
    at ResolutionRequest.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
