### ISSUE TITLE
populate wipes out unused data

### ISSUE THREAD

**Issue by benoj** [prescottprue/react-redux-firebase#192] opened 2017-07-11 19:59 UTC
Given the following data:
```
{
  "organisations" : {
    "ygsdyua" : {
      "jobData" : {
        "-Kon1TZ3PunCmKK_TTXm" : {
          "tags" : [ "jgsdasd", "jksad" ]
        },
    
      },
      "tags" : {
        "jasdad" : {
          "name" : "Unused"
        },
        "jgsdasd" : {
          "name" : "Python"
        },
        "jguiwadazdcb" : {
          "name" : "Java"
        }
      }
    }
  }
}

```

When I run a populate across JobData and tags in one component (below)
```
const getPopulates = (org) => [
  { child: 'tags', root: `/organisations/${org}/tags`, childParam: 'name' }
]

@firebaseConnect(({currentOrg}) => {
  const populates =  getPopulates(currentOrg)
  return [
    { path: `/organisations/${currentOrg}/jobData`, populates }
  ]
})
```

and then have another component dependent on tags:
```
@firebaseConnect(({currentOrg}) => {[
  {path:`/organisations/${currentOrg}/tags`}
]})
```

the component dependent on tags is only given the data which has been populated. In this instance I can only see tags which have been used on jobs. But I need an entire list of the tags.

**Comment by prescottprue** [comment] 2017-07-12 02:05
I believe this is a duplicate of #130, so going to close. Please correct my if I am wrong, or the following answer doesn't clarify.

#### Current Solution
If I am understanding your example correctly, you should be able to use [`storeAs`](http://docs.react-redux-firebase.com/history/v1.5.0/docs/queries.html) (mentioned in  [the `v1.5.0` docs](http://docs.react-redux-firebase.com/history/v1.5.0/docs/queries.html)). It will allow you to store your query somewhere else in redux state other than the query path (where it is stored by default).

In your component:

```js
@firebaseConnect(({ currentOrg }) => {[
  { path:`/organisations/${currentOrg}/tags`, storeAs: `tagsByOrg/${currentOrg}` }
]})
@connect(({ firebase }, { currentOrg }) => ({
  tags: dataToJS(firebase, `tagsByOrg/${currentOrg}`) // use your storeAs path here instead of the query path
})
```

This places them into redux under a different path you provided (instead of under the same path as the populate in your other query).

#### Future

Keeping #130 open so that a more clear solution can be figured out on the populate side, it will most likely involve giving populate `storeAs` capability.


#### Side Note

It might make things easier on you if you change up the whole data structure a bit (not sure if your project is still at the state where that is possible).

Normalizing and using keys as pointers is a great pattern to follow (reason populate is nice), so if you are planning to do that, you should model around that like so:

```js
{
    "tags" : { //
      "jasdad" : {
        "name" : "Unused"
      },
      "jgsdasd" : {
        "name" : "Python"
      },
      "jguiwadazdcb" : {
        "name" : "Java"
      }
  }
  "organisations" : {
    "ygsdyua" : {
      "jobData" : {
        "-Kon1TZ3PunCmKK_TTXm" : {
          "tags" : [ "jgsdasd", "jksad" ]
        },
      },
    }
  }
}
```

populates could then look something like this (not dependent on organization, but still only loads tags used by the organization):

```js
 const populates = [
  { child: 'tags', root: 'tags', childParam: 'name' }
]

@firebaseConnect(({ currentOrg }) => {
  return [
    { path: `/organisations/${currentOrg}/jobData`, populates }
  ]
})
@connect(({ firebase }, { currentOrg }) => ({
  tags: populatedDataToJS(firebase, `/organisations/${currentOrg}/jobData`, populates)
```

**Main changes** :
* Tags are at the top level along side organizations instead of inside of them - so different organizations can use the same tags (seems to be the reason for calling it a "tag")
* Tags under `jobData` are `$key: true` instead of an array - Makes adding/updating/deleting much easier since you can update/delete by that key instead of needing to go to and from an array (loading data first then using `splice`). Also, when adding a new tag, you can easily see which tags have already been used without needing to do `indexOf` (not really a huge concern since populate can do this part)

**Closed** 2017-07-12 02:06 UTC

**Comment by benoj** [comment] 2017-07-13 14:43
Thanks @prescottprue for coming back so quickly. I should mention that `storeAs` did not work for me when i did this at a child component level (where the parent was dependent on the populated fields). In order to get `storeAs` to work I had to pull this to the parent _and_ have this before the populated path
