### ISSUE TITLE
Accessing  profile '/account'  errors

### ISSUE THREAD

**Issue by magicman179** [prescottprue/react-redux-firebase#54] opened 2017-02-02 04:21 UTC
I am trying to access the profile menu in the example w/ material given. But I am not getting the right menu to access it.  I get this on the home page in errors:
Warning: Failed propType: Required prop `message` was not specified in `Snackbar`. Check the render method of `Home`.  warning.js?:45:9
Warning: Failed propType: Required prop `message` was not specified in `SnackbarBody`. Check the render method of `WithWidth`.

Even when trying to access '/account' directly I get full errors.
connect.js:81 Uncaught TypeError: Cannot read property 'firebase' of undefined
    at FirebaseConnect.componentWillMount (connect.js:81)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:210)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (ReactPerf.js:66)
    at Object.mountComponent (ReactReconciler.js:37)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:241)
    at ReactDOMComponent._createContentMarkup (ReactDOMComponent.js:591)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:479)
    at Object.mountComponent (ReactReconciler.js:37)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:225)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (ReactPerf.js:66)

I only changed the config values for firebase  for the example. Is there something else I need to do on firebase or the src?

**Comment by prescottprue** [comment] 2017-02-02 05:39
What are the rules on your Firebase instance? If not set correctly, it can keep your account from being created (thus the menu will not show it).

The warnings should not change how anything is functioning .

**Comment by magicman179** [comment] 2017-02-02 22:05
rules are {
  "rules": {
    ".read": "auth != true",
    ".write": "auth != true"
  }
}

**Comment by prescottprue** [comment] 2017-02-02 22:11
1. Not sure if `auth != true` is what you want. Try this for rules instead:
```
{
  "rules": {
    ".read": "auth !== null",
    ".write": "auth !== null"
  }
}
```

2. Have you authenticated?

Can you possibly link to the repository so that I can attempt to reproduce? It is also good for me to confirm versions of everything.

**Comment by magicman179** [comment] 2017-02-03 01:00
Yes I have authenticated. I was going to upload the repository but I tried the example/material on this repository (with no edits) installed it, and ran it. But, I got the same problem and not being able to access '/account'. Can you verify this?

**Comment by DeividasK** [comment] 2017-02-03 12:35
Your rules
```js
"rules": {
  ".read": "auth != true",
  ".write": "auth != true"
}
```
mean that if user is authenticated, he cannot access the data. As Scott suggessted, try changing the rules.

**Comment by prescottprue** [comment] 2017-02-08 08:46
@magicman179 Try the [`material-example` branch](https://github.com/prescottprue/react-redux-firebase/tree/material-example). It isn't finished yet, but that issue should be fixed.

The plan is to make it an a "real-world" example using [`generator-react-firebase`](https://github.com/prescottprue/generator-react-firebase) as the starting place. Feel free to reach out in the PR or over [gitter](https://gitter.im/redux-firebase/Lobby) if you have any suggestions on changes/improvements.

Will leave this issue open for a to get a chance to test the example out.

**Comment by prescottprue** [comment] 2017-02-14 08:31
The [`v1.3.0-alpha` release](https://github.com/prescottprue/react-redux-firebase/releases/edit/v1.3.0-alpha) includes major changes to the material example. It is also now available at [demo.react-redux-firebase.com](https://demo.react-redux-firebase.com).

Since it is a major overhaul, I am going to close this issue. Feel free to post a new issue if you find anything not working as expected.

**Closed by prescottprue** 2017-02-14 08:31 UTC
Labels: question
