### ISSUE TITLE
Deleting an item from a nested collection of a document does not update redux store

### ISSUE THREAD

**Issue by vijayst** [prescottprue/react-redux-firebase#642] opened 2019-02-24 14:30 UTC
**Do you want to request a *feature* or report a *bug*?**  
Bug. 

I have a user document with nested photos collection. 
![screenshot 2019-02-24 at 7 26 05 pm](https://user-images.githubusercontent.com/3457565/53300474-d228f100-386d-11e9-8f19-6fa1e5440ff7.jpg)

On removing a photo from the user document, a redux firestore listener event is triggered with the following payload
![screenshot 2019-02-24 at 7 50 04 pm](https://user-images.githubusercontent.com/3457565/53300483-ea990b80-386d-11e9-9cc9-c8c280e7c1ee.jpg)

**What is the current behavior?**
The user document is not updated with the payload

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
Create a collection with a nested collection
Select a document
Delete an item from the nested collection of the document
The document does not get updated in the redux store

[Sample Repo](https://github.com/vijayst/revents)
[File](https://github.com/vijayst/revents/blob/master/src/settings/actions.js)
Check deletePhoto function.

**What is the expected behavior?**
The user document should be updated and there should be one photo less.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
MacOS latest, Chrome latest.

**Comment by pROFESOR11** [comment] 2019-02-24 21:39
+1.
The store is updated when I use `arrayUnion` method, but the store is not updated when I use `arrayRemove` method.
I also noticed that: `firestore.data` path is updated, but `firestore.ordered` is not! They are not same when remove method is used..

**Comment by prescottprue** [comment] 2019-02-25 00:31
I think this is a duplicate of [115 on redux-firestore](https://github.com/prescottprue/redux-firestore/issues/115). Try using `storeAs` so that the data is not as deeply nested.

The v1.0.0 pre-releases (available on the `alpha` tag) may be of help. As described [in the v1.0.0 Roadmap](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap), the new versions store sub-collections at the top level along side collections in redux state since there were a number of issues reported with deep updates.

**Comment by pROFESOR11** [comment] 2019-02-25 08:41
Hi @prescottprue,
I have now checked the docs, it also advises to use storeAs. I will check and get back soon.

**Comment by Aparus** [comment] 2019-03-10 05:57
+1. 
I think my issue the same. [Array field updates on the client (firestoreConnect) only when I add to it items. But not updates when I remove from it items.](https://github.com/prescottprue/react-redux-firebase/issues/648)

In my case array field updates when I add to it new elements. But doesn't updated when I remove elements.

**Comment by pROFESOR11** [comment] 2019-03-10 05:59
Hi @Aparus,
Using storeAs fixed the problem in my case. You should give it a try!

**Comment by Aparus** [comment] 2019-03-10 07:40
@pROFESOR11 , i didn't understand how to use storeAs ) but I fixed the problem with update redux-firestore to 0.7.1 version , which released about 2 weeks ago )

**Comment by prescottprue** [comment] 2019-03-10 19:39
Going to close this since the newer versions of redux-firestore fix the issue, and it can also be worked around using `storeAs`. Thanks to all for input.

**Closed by prescottprue** 2019-03-10 19:39 UTC
